export const chartConfig = {
  distance: { label: "Distance (mi)", color: "hsl(var(--accent))" },
  upperBody: { label: "Upper Body", color: "hsl(var(--chart-1))" },
  fullBody: { label: "Full Body", color: "hsl(var(--chart-2))" },
  lowerBody: { label: "Lower Body", color: "hsl(var(--chart-3))" },
  cardio: { label: "Cardio", color: "hsl(var(--chart-4))" },
  core: { label: "Core", color: "hsl(var(--chart-5))" },
  other: { label: "Other", color: "hsl(var(--chart-6))" },
  value: { label: "Value", color: "hsl(var(--accent))" },
  e1RM: { label: "Est. 1-Rep Max (lbs)", color: "hsl(var(--primary))" },
  volume: { label: "Volume (lbs)", color: "hsl(var(--chart-2))"},
  actualPR: { label: "Actual PR", color: "hsl(var(--accent))" },
  trend: { label: "e1RM Trend", color: "hsl(var(--muted-foreground))" },
  Running: { label: "Running", color: "hsl(var(--chart-1))" },
  Walking: { label: "Walking", color: "hsl(var(--chart-2))" },
  Cycling: { label: "Cycling", color: "hsl(var(--chart-3))" },
  Climbmill: { label: "Climbmill", color: "hsl(var(--chart-4))" },
  Rowing: { label: "Rowing", color: "hsl(var(--chart-5))" },
  Swimming: { label: "Swimming", color: "hsl(var(--chart-6))" },
} satisfies ChartConfig;