
name: Deploy to Firebase Hosting on merge to main
'on':
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  build_and_deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - name: Create .env.production.local file
        run: echo "${{ secrets.ENV_PRODUCTION }}" > .env.production.local
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FITNESSAI_PROD }}'
          channelId: live
          projectId: fitnessai-prod
